### ISSUE TITLE
PBI doesn't look like what you put here

### ISSUE THREAD

**Issue by RowlinAPsychologist** [MicrosoftDocs/powerbi-docs.zh-cn#70]
I tried to find the copy button (and the all the following functions) in the latest Desktop version and Web version. But I couldn't! Which version was this instruction referring to? How can I copy a chart in the lastest PBI?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 00479245-9654-ad47-b2d5-12f1e36ccdc9
* Version Independent ID: b46f2147-f0e8-cad0-7240-28b7231ae70d
* Content: [在 Power BI 中复制并粘贴可视化效果 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/visuals/power-bi-visualization-copy-paste)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-copy-paste.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/visuals/power-bi-visualization-copy-paste.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by srvbpigh** [comment]
Hello, @RowlinAPsychologist
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #2235](https://github.com/MicrosoftDocs/powerbi-docs/issues/2235) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @RowlinAPsychologist, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/2235. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
